// Datos de muestra que se usan SOLO si todavía no conectaste Supabase
// (no hay NEXT_PUBLIC_SUPABASE_URL configurado) o mientras no cargaste
// tus propios productos desde el panel de administrador.
// Apenas conectes Supabase y cargues productos reales, esto se deja de usar.
import { Category, Product } from "./types";

export const seedCategories: Category[] = [
  {
    id: "seed-cat-tortas",
    name: "Tortas",
    slug: "tortas",
    position: 1,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "seed-cat-cheesecakes",
    name: "Cheesecakes",
    slug: "cheesecakes",
    position: 2,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "seed-cat-cajas",
    name: "Cajas y mini postres",
    slug: "cajas-y-mini-postres",
    position: 3,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "seed-cat-granolas",
    name: "Granolas",
    slug: "granolas",
    position: 4,
    active: true,
    created_at: new Date().toISOString(),
  },
];

const now = new Date().toISOString();

export const seedProducts: Product[] = [
  {
    id: "seed-prod-mousse-choco",
    category_id: "seed-cat-tortas",
    name: "Torta mousse de chocolate con garrapiñada",
    slug: "torta-mousse-chocolate-garrapinada",
    description:
      "Mousse de chocolate semiamargo, bizcochuelo húmedo y garrapiñada crocante por encima. Una de nuestras tortas más pedidas.",
    size_label: "Torta entera - 10 a 12 porciones",
    price: 32000,
    promo_price: null,
    promo_active: false,
    images: ["/images/products/torta-mousse-chocolate-garrapinada.webp"],
    position: 1,
    active: true,
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-prod-choco-ganache",
    category_id: "seed-cat-tortas",
    name: "Torta de chocolate con ganache",
    slug: "torta-chocolate-ganache",
    description:
      "Bizcochuelo de chocolate, relleno de dulce de leche y cubierta de ganache de chocolate con decoración a manga.",
    size_label: "Torta entera - 10 a 12 porciones",
    price: 30000,
    promo_price: null,
    promo_active: false,
    images: ["/images/products/torta-chocolate-ganache.webp"],
    position: 2,
    active: true,
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-prod-crumble-blanca",
    category_id: "seed-cat-tortas",
    name: "Torta de crumble",
    slug: "torta-crumble-blanca",
    description:
      "Bizcochuelo relleno con crema y cubierto con crumble crocante casero. Suave, cremosa y no demasiado dulce.",
    size_label: "Torta entera - 10 a 12 porciones",
    price: 29000,
    promo_price: null,
    promo_active: false,
    images: ["/images/products/torta-crumble-blanca.webp"],
    position: 3,
    active: true,
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-prod-milhojas",
    category_id: "seed-cat-tortas",
    name: "Mil hojas de dulce de leche",
    slug: "milhojas-dulce-de-leche",
    description:
      "Capas de masa hojaldrada bien crocante, dulce de leche y un toque de merengue tostado arriba. Clásico de siempre.",
    size_label: "Entera - 10 a 12 porciones",
    price: 31000,
    promo_price: null,
    promo_active: false,
    images: ["/images/products/milhojas-dulce-de-leche.webp"],
    position: 4,
    active: true,
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-prod-cheesecake-vasco",
    category_id: "seed-cat-cheesecakes",
    name: "Cheesecake vasco",
    slug: "cheesecake-vasco",
    description:
      "Cheesecake estilo vasco, cremoso por dentro y bien tostado por fuera. Se sirve solo o con coulis de frutos rojos.",
    size_label: "Entero - 10 a 12 porciones",
    price: 28000,
    promo_price: null,
    promo_active: false,
    images: [
      "/images/products/cheesecake-vasca-entera.webp",
      "/images/products/cheesecake-vasca-frutos-rojos.webp",
    ],
    position: 1,
    active: true,
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-prod-caja-mini",
    category_id: "seed-cat-cajas",
    name: "Caja de mini postres surtidos",
    slug: "caja-mini-postres-surtidos",
    description:
      "Selección de 6 mini postres: brownie, cheesecake de frutos rojos, lemon pie, crumble, budín y limón. Ideal para compartir o regalar.",
    size_label: "Caja x6 unidades",
    price: 12000,
    promo_price: null,
    promo_active: false,
    images: ["/images/products/box-mini-postres.webp"],
    position: 1,
    active: true,
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-prod-granola",
    category_id: "seed-cat-granolas",
    name: "Granola artesanal con frutos secos",
    slug: "granola-artesanal-frutos-secos",
    description:
      "Granola horneada casera con avena, almendras, maní, avellanas y pasas. Sin conservantes.",
    size_label: "Bolsa x500g",
    price: 6500,
    promo_price: null,
    promo_active: false,
    images: ["/images/products/granola-artesanal.webp"],
    position: 1,
    active: true,
    featured: false,
    created_at: now,
    updated_at: now,
  },
];
